/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as AttributionRouteImport } from './routes/attribution'
import { Route as IndexRouteImport } from './routes/index'

const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const AttributionRoute = AttributionRouteImport.update({
  id: '/attribution',
  path: '/attribution',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attribution': typeof AttributionRoute
  '/developers': typeof DevelopersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attribution': typeof AttributionRoute
  '/developers': typeof DevelopersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attribution': typeof AttributionRoute
  '/developers': typeof DevelopersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/attribution' | '/developers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/attribution' | '/developers'
  id: '__root__' | '/' | '/attribution' | '/developers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttributionRoute: typeof AttributionRoute
  DevelopersRoute: typeof DevelopersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attribution': {
      id: '/attribution'
      path: '/attribution'
      fullPath: '/attribution'
      preLoaderRoute: typeof AttributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttributionRoute: AttributionRoute,
  DevelopersRoute: DevelopersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
